id: d9e8cc5e33934975a7006e25cfcd8bd9
title: Toh_244-Proper_Dharma_Conduct-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-066-002
  eft-text-version: 1.1.2 2020
